namespace cuatroSegregacionRefactory;
//CREACION DE UNA INTERFAZ DE ALTO NIVEL
interface IMultiCompleto: IFax,IMultiBasico {
///ESTA CLASE TENDRA LA IMPLEMENTACION DE FAX Y MULTIBAICO PARA AQUELLA CLASE QUE NECESITE LOS CUATROS METODOS
}